### ISSUE TITLE
feature/backend writing file for user's algorithm's json string

### ISSUE THREAD

**Issue by zhTnecniv** [NVMS1709/capstone#30]
For features, please specify at least minimal requirements, e.g.:

* "As a developer, I want to set up a route " POST /api/algorithm-execution" to receive user's algorithm input which will be "req.body.algorithmContent"."
* "In this route, I want to write a file with the user algorithm' input and export the entry function "BST" of that algorithm at the end of the file."

**Comment by mr4227** [comment]
item  closed
